
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 14 22:32:32 CST 2020
//----------------------------------------------------

package analisis.cpp.importaciones;

import comprobaciones.ComprobadorAmbito;
import comprobaciones.ComprobadorTipos;
import comprobaciones.Nodo;
import comprobaciones.NodoPY;
import java_cup.runtime.Symbol;
import java.util.ArrayList;
import simbolos.Simbolo;
import simbolos.TablaSimbolos;
import tresdirecciones.*;
import errores.ErrorG;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Wed Oct 14 22:32:32 CST 2020
  */
public class AnalizadorSintacticoIm extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public AnalizadorSintacticoIm() {super();}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintacticoIm(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintacticoIm(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\017\000\002\002\004\000\002\005\002\000\002\002" +
    "\006\000\002\006\002\000\002\002\005\000\002\004\002" +
    "\000\002\007\002\000\002\003\005\000\002\010\002\000" +
    "\002\003\005\000\002\011\002\000\002\003\005\000\002" +
    "\012\002\000\002\003\005\000\002\003\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\026\000\006\003\004\004\006\001\002\000\004\002" +
    "\ufffe\001\002\000\004\002\026\001\002\000\014\004\000" +
    "\005\000\006\000\007\000\010\000\001\002\000\014\004" +
    "\ufff3\005\013\006\011\007\014\010\010\001\002\000\014" +
    "\004\ufff5\005\ufff5\006\ufff5\007\ufff5\010\ufff5\001\002\000" +
    "\014\004\ufff9\005\ufff9\006\ufff9\007\ufff9\010\ufff9\001\002" +
    "\000\004\004\021\001\002\000\014\004\ufffb\005\ufffb\006" +
    "\ufffb\007\ufffb\010\ufffb\001\002\000\014\004\ufff7\005\ufff7" +
    "\006\ufff7\007\ufff7\010\ufff7\001\002\000\014\004\ufff3\005" +
    "\013\006\011\007\014\010\010\001\002\000\004\004\ufff6" +
    "\001\002\000\014\004\ufff3\005\013\006\011\007\014\010" +
    "\010\001\002\000\004\004\ufffa\001\002\000\004\002\uffff" +
    "\001\002\000\014\004\ufff3\005\013\006\011\007\014\010" +
    "\010\001\002\000\004\004\ufff8\001\002\000\014\004\ufff3" +
    "\005\013\006\011\007\014\010\010\001\002\000\004\004" +
    "\ufff4\001\002\000\004\002\001\001\002\000\004\002\ufffc" +
    "\001\002\000\004\002\ufffd\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\026\000\004\002\004\001\001\000\004\006\026\001" +
    "\001\000\002\001\001\000\004\005\006\001\001\000\004" +
    "\003\011\001\001\000\004\012\023\001\001\000\004\010" +
    "\021\001\001\000\002\001\001\000\004\007\016\001\001" +
    "\000\004\011\014\001\001\000\004\003\015\001\001\000" +
    "\002\001\001\000\004\003\017\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\003\022\001\001\000\002\001" +
    "\001\000\004\003\024\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\004\027\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$AnalizadorSintacticoIm$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$AnalizadorSintacticoIm$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$AnalizadorSintacticoIm$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public ArrayList<Simbolo> listaS = new ArrayList<>();
    public ArrayList<Cuarteto> listaC = new ArrayList<>();
    public boolean correcto = false;
    public int tipo = 0;
    
    public void setLista(ArrayList<Simbolo> listaS){
        this.listaS = listaS;
    }
    


    private Symbol s;
    public void syntaxError(Symbol s){
        this.s = s;
    }
    public Symbol getS(Symbol s){
        return this.s = s;
    }

    public void setAccion(String tipo,String mensaje,String accion){
            System.out.println(tipo+"         "+mensaje);
    }

    public void syntax_error(Symbol s){
            if(s!=null){
                //ErrorG e = new ErrorG(s.right,s.left,(String) s.value,"Sintactico","Error Sintaxis token: "+(String) s.value+" ------ Linea: " + (s.right+1) + ",   Columna: " + (s.left+1));
                //listaErrores.add(e);
                /*Error error = new Error((String) s.value,s.right, s.left, 2, "Error Sintaxis token: "+(String) s.value+" ------ Linea: " + (s.right+1) + ",   Columna: " + (s.left+1));
                erroresSintacticos.add(error);*/
                setAccion("ERROR","Error Sintaxis token: Linea: " + ((int)s.right+1) + ",   Columna: " + ((int)s.left+1) + ",  Simbolo: " + s.value, "");
            }
    }


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$AnalizadorSintacticoIm$actions {


    String cadena = "";
    ArrayList<Simbolo> listaS = new ArrayList<>();
    int contador = 0;

  private final AnalizadorSintacticoIm parser;

  /** Constructor */
  CUP$AnalizadorSintacticoIm$actions(AnalizadorSintacticoIm parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$AnalizadorSintacticoIm$do_action(
    int                        CUP$AnalizadorSintacticoIm$act_num,
    java_cup.runtime.lr_parser CUP$AnalizadorSintacticoIm$parser,
    java.util.Stack            CUP$AnalizadorSintacticoIm$stack,
    int                        CUP$AnalizadorSintacticoIm$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$AnalizadorSintacticoIm$result;

      /* select the action based on the action number */
      switch (CUP$AnalizadorSintacticoIm$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // codigos ::= 
            {
              Object RESULT =null;
		if(cadena!=null && !cadena.isEmpty()){
                        parser.listaC.add(new Cuarteto("PRINT","\""+cadena+"\"","","",8));
                    } cadena = "";
              CUP$AnalizadorSintacticoIm$result = parser.getSymbolFactory().newSymbol("codigos",1, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoIm$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // codigos ::= TEXTO NT$5 codigos 
            {
              Object RESULT =null;
              // propagate RESULT from NT$5
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoIm$stack.elementAt(CUP$AnalizadorSintacticoIm$top-1)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.elementAt(CUP$AnalizadorSintacticoIm$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.elementAt(CUP$AnalizadorSintacticoIm$top-2)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoIm$stack.elementAt(CUP$AnalizadorSintacticoIm$top-2)).value;

              CUP$AnalizadorSintacticoIm$result = parser.getSymbolFactory().newSymbol("codigos",1, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.elementAt(CUP$AnalizadorSintacticoIm$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoIm$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // NT$5 ::= 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoIm$stack.peek()).value;
cadena += (String) a;
              CUP$AnalizadorSintacticoIm$result = parser.getSymbolFactory().newSymbol("NT$5",8, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoIm$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // codigos ::= C NT$4 codigos 
            {
              Object RESULT =null;
              // propagate RESULT from NT$4
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoIm$stack.elementAt(CUP$AnalizadorSintacticoIm$top-1)).value;

              CUP$AnalizadorSintacticoIm$result = parser.getSymbolFactory().newSymbol("codigos",1, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.elementAt(CUP$AnalizadorSintacticoIm$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoIm$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // NT$4 ::= 
            {
              Object RESULT =null;

                    if(cadena!=null && !cadena.isEmpty()){
                        parser.listaC.add(new Cuarteto("PRINT","\""+cadena+"\"","","",8));
                    }
                    if(listaS.size()>0 && listaS.size()-1<=contador){
                        if(listaS.get(contador).getTipo().equals("Integer")){
                            if(parser.tipo==1){
                                parser.listaC.add(new Cuarteto("SCANF","\"%c\"","",listaS.get(contador).getNombre()+"",8));
                            }else{
                                parser.listaC.add(new Cuarteto("PRINT","\"%c\","+listaS.get(contador).getNombre(),"","",8));
                            }
                        }else{parser.correcto = false;}
                        
                        contador++;
                    }else{parser.correcto = false;}
                    
                    cadena = "";
              CUP$AnalizadorSintacticoIm$result = parser.getSymbolFactory().newSymbol("NT$4",7, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoIm$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // codigos ::= F NT$3 codigos 
            {
              Object RESULT =null;
              // propagate RESULT from NT$3
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoIm$stack.elementAt(CUP$AnalizadorSintacticoIm$top-1)).value;

              CUP$AnalizadorSintacticoIm$result = parser.getSymbolFactory().newSymbol("codigos",1, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.elementAt(CUP$AnalizadorSintacticoIm$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoIm$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // NT$3 ::= 
            {
              Object RESULT =null;

                    if(cadena!=null && !cadena.isEmpty()){
                        parser.listaC.add(new Cuarteto("PRINT","\""+cadena+"\"","","",8));
                    }
                    if(listaS.size()>0 && listaS.size()-1<=contador){
                        if(listaS.get(contador).getTipo().equals("Integer")){
                            if(parser.tipo==1){
                                parser.listaC.add(new Cuarteto("SCANF","\"%f\"","",listaS.get(contador).getNombre()+"",8));
                            }else{
                                parser.listaC.add(new Cuarteto("PRINT","\"%f\","+listaS.get(contador).getNombre(),"","",8));
                            }
                        }else{parser.correcto = false;}
                        
                        contador++;
                    }else{parser.correcto = false;}
                    
                    cadena = "";
              CUP$AnalizadorSintacticoIm$result = parser.getSymbolFactory().newSymbol("NT$3",6, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoIm$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // codigos ::= D NT$2 codigos 
            {
              Object RESULT =null;
              // propagate RESULT from NT$2
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoIm$stack.elementAt(CUP$AnalizadorSintacticoIm$top-1)).value;

              CUP$AnalizadorSintacticoIm$result = parser.getSymbolFactory().newSymbol("codigos",1, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.elementAt(CUP$AnalizadorSintacticoIm$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoIm$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // NT$2 ::= 
            {
              Object RESULT =null;

                    if(cadena!=null && !cadena.isEmpty()){
                        parser.listaC.add(new Cuarteto("PRINT","\""+cadena+"\"","","",8));
                    }
                    if(listaS.size()>0 && listaS.size()-1<=contador){
                        if(listaS.get(contador).getTipo().equals("Integer")){
                            if(parser.tipo==1){
                                parser.listaC.add(new Cuarteto("SCANF","\"%d\"","",listaS.get(contador).getNombre()+"",8));
                            }else{
                                parser.listaC.add(new Cuarteto("PRINT","\"%d\","+listaS.get(contador).getNombre(),"","",8));
                            }
                        }else{parser.correcto = false;}
                        
                        contador++;
                    }else{parser.correcto = false;}
                    
                    cadena = "";
              CUP$AnalizadorSintacticoIm$result = parser.getSymbolFactory().newSymbol("NT$2",5, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoIm$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // er ::= 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoIm$result = parser.getSymbolFactory().newSymbol("er",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoIm$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // INICIO ::= error NT$1 er 
            {
              Object RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoIm$stack.elementAt(CUP$AnalizadorSintacticoIm$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.elementAt(CUP$AnalizadorSintacticoIm$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.elementAt(CUP$AnalizadorSintacticoIm$top-2)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoIm$stack.elementAt(CUP$AnalizadorSintacticoIm$top-2)).value;

              CUP$AnalizadorSintacticoIm$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.elementAt(CUP$AnalizadorSintacticoIm$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoIm$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // NT$1 ::= 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoIm$stack.peek()).value;
parser.syntax_error((Symbol)e); 
              CUP$AnalizadorSintacticoIm$result = parser.getSymbolFactory().newSymbol("NT$1",4, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoIm$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // INICIO ::= COMILLAS NT$0 codigos COMILLAS 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoIm$stack.elementAt(CUP$AnalizadorSintacticoIm$top-2)).value;

              CUP$AnalizadorSintacticoIm$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.elementAt(CUP$AnalizadorSintacticoIm$top-3)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoIm$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // NT$0 ::= 
            {
              Object RESULT =null;

                    listaS = parser.listaS;
                    contador = 0;
                    parser.correcto = true;
                    
            
              CUP$AnalizadorSintacticoIm$result = parser.getSymbolFactory().newSymbol("NT$0",3, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoIm$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.elementAt(CUP$AnalizadorSintacticoIm$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.elementAt(CUP$AnalizadorSintacticoIm$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoIm$stack.elementAt(CUP$AnalizadorSintacticoIm$top-1)).value;
		RESULT = start_val;
              CUP$AnalizadorSintacticoIm$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.elementAt(CUP$AnalizadorSintacticoIm$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoIm$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$AnalizadorSintacticoIm$parser.done_parsing();
          return CUP$AnalizadorSintacticoIm$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

