
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 03 22:09:06 CST 2020
//----------------------------------------------------

package analisis.cpp.importaciones;

/** CUP generated class containing symbol constants. */
public class SimbolosIm {
  /* terminals */
  public static final int ASTERISCO = 10;
  public static final int DECIMAL = 9;
  public static final int PUNTO = 6;
  public static final int VB = 2;
  public static final int PY = 4;
  public static final int EOF = 0;
  public static final int JV = 3;
  public static final int NUMERO = 8;
  public static final int COMILLAS = 5;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 7;
}

