
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 14 22:32:32 CST 2020
//----------------------------------------------------

package analisis.cpp.importaciones;

/** CUP generated class containing symbol constants. */
public class SimbolosIm {
  /* terminals */
  public static final int TEXTO = 6;
  public static final int error = 1;
  public static final int F = 4;
  public static final int D = 3;
  public static final int C = 5;
  public static final int COMILLAS = 2;
  public static final int EOF = 0;
}

