
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Oct 02 18:51:13 CST 2020
//----------------------------------------------------

package analisis.java;

/** CUP generated class containing symbol constants. */
public class SimbolosJAVA {
  /* terminals */
  public static final int MAS_MAS = 52;
  public static final int NUMERO = 41;
  public static final int SEPARADOR_JAVA = 2;
  public static final int POR = 13;
  public static final int CHAR = 7;
  public static final int LLAVES_C = 47;
  public static final int LLAVES_A = 46;
  public static final int COMENTARIO_VARIOS = 22;
  public static final int CASE = 33;
  public static final int DIFERENTE = 20;
  public static final int MENOS_MENOS = 53;
  public static final int DOS_PUNTOS = 43;
  public static final int CORCHETE_C = 45;
  public static final int INT = 5;
  public static final int CORCHETE_A = 44;
  public static final int FOR = 27;
  public static final int IDENTIFICADOR = 39;
  public static final int NOT = 10;
  public static final int SOUT = 23;
  public static final int AND = 8;
  public static final int IGUAL = 19;
  public static final int OR = 9;
  public static final int CLASS = 4;
  public static final int DIV = 14;
  public static final int INTINPUT = 24;
  public static final int IF = 30;
  public static final int IGUAL_IGUAL = 54;
  public static final int PUNTO_COMA = 48;
  public static final int DECIMAL = 40;
  public static final int EOF = 0;
  public static final int RETURN = 37;
  public static final int SEPARADOR_PROGRAMA = 3;
  public static final int error = 1;
  public static final int COMA = 49;
  public static final int MENOS = 12;
  public static final int MAYOR_QUE = 16;
  public static final int BREAK = 34;
  public static final int VOID = 36;
  public static final int SWITCH = 32;
  public static final int COMENTARIO_SIMPLE = 21;
  public static final int VALOR = 42;
  public static final int ELSE = 31;
  public static final int PARENTESIS_C = 51;
  public static final int FLOATINPUT = 25;
  public static final int WHILE = 28;
  public static final int PARENTESIS_A = 50;
  public static final int DEFAULT = 35;
  public static final int MAYOR_IGUAL = 18;
  public static final int PUBLIC = 38;
  public static final int FLOAT = 6;
  public static final int CHARINPUT = 26;
  public static final int MENOR_QUE = 15;
  public static final int TEXTO = 55;
  public static final int MENOR_IGUAL = 17;
  public static final int DO = 29;
  public static final int MAS = 11;
}

