/* The following code was generated by JFlex 1.4.3 on 27/09/20 12:03 PM */

package analisis.py;
import java_cup.runtime.*;
import java.util.ArrayList;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 27/09/20 12:03 PM from the specification file
 * <tt>LexicoPY.jflex</tt>
 */
public class AnalizadorLexicoPY implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  6, 51, 10,  0,  0,  6,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     6,  1, 33, 32,  0,  7,  1, 50, 36, 58, 27, 25, 57, 26, 49, 28, 
     5,  5,  5,  5,  5,  5,  5,  5,  5,  5, 52, 48, 29, 31, 30,  0, 
     1, 12,  9,  2,  2,  2,  2, 17,  2,  2, 11,  2,  2, 18,  2, 16, 
    13,  2, 15,  2,  2,  2,  8,  2,  2, 14,  2, 53,  0, 54,  0, 42, 
     0, 19, 46, 40, 21, 44, 38,  2, 41, 35,  2, 47, 39,  2, 20, 22, 
    34,  2, 23, 45, 24, 37,  2, 43,  2,  2,  2, 55,  1, 56,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\4\1\1\1\5"+
    "\5\2\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\2\1\2\2\1\15\2\2\1\16\3\2\1\1\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\3\0"+
    "\3\2\1\27\1\2\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\0\1\36\1\0\1\37\1\2\1\40\1\41"+
    "\6\2\3\0\1\42\1\3\2\0\1\43\1\44\1\45"+
    "\1\2\2\37\2\2\1\46\6\2\1\42\3\0\1\2"+
    "\2\0\1\37\5\2\1\47\1\50\1\2\2\0\1\2"+
    "\1\0\1\37\4\2\1\51\1\2\2\0\1\52\1\0"+
    "\1\53\1\54\3\2\1\55\2\0\1\53\3\2\2\0"+
    "\1\56\2\2\2\0\1\2\1\57\1\0\1\60\1\61"+
    "\3\0\2\62";

  private static int [] zzUnpackAction() {
    int [] result = new int[149];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\73\0\166\0\261\0\354\0\u0127\0\u0162\0\73"+
    "\0\u019d\0\u01d8\0\u0213\0\u024e\0\u0289\0\73\0\73\0\u02c4"+
    "\0\u02ff\0\u033a\0\u0375\0\u03b0\0\u03eb\0\u0426\0\u0461\0\u049c"+
    "\0\73\0\u04d7\0\u0512\0\73\0\u054d\0\u0588\0\u05c3\0\u05fe"+
    "\0\73\0\73\0\73\0\73\0\73\0\73\0\73\0\73"+
    "\0\261\0\u0639\0\u0674\0\u06af\0\u06ea\0\u0725\0\166\0\u0760"+
    "\0\73\0\73\0\73\0\73\0\73\0\73\0\u03eb\0\73"+
    "\0\u079b\0\u07d6\0\u0811\0\u084c\0\166\0\u0887\0\u08c2\0\u08fd"+
    "\0\u0938\0\u0973\0\u09ae\0\u09e9\0\u0a24\0\u0a5f\0\u09e9\0\u0639"+
    "\0\u0a9a\0\u0ad5\0\166\0\166\0\166\0\u0b10\0\u079b\0\u0b4b"+
    "\0\u0b86\0\u0bc1\0\166\0\u0bfc\0\u0c37\0\u0c72\0\u0cad\0\u0ce8"+
    "\0\u0d23\0\73\0\u0d5e\0\u0d99\0\u0dd4\0\u0e0f\0\u0b4b\0\u0e4a"+
    "\0\u0e85\0\u0ec0\0\u0efb\0\u0f36\0\u0f71\0\u0fac\0\166\0\166"+
    "\0\u0fe7\0\u1022\0\u105d\0\u1098\0\u10d3\0\u110e\0\u1149\0\u1184"+
    "\0\u11bf\0\u11fa\0\166\0\u1235\0\u1270\0\u12ab\0\166\0\u12e6"+
    "\0\u110e\0\73\0\u1321\0\u135c\0\u1397\0\73\0\u13d2\0\u140d"+
    "\0\u12e6\0\u1448\0\u1483\0\u14be\0\u14f9\0\u1534\0\166\0\u156f"+
    "\0\u15aa\0\u15e5\0\u1620\0\u165b\0\166\0\u1696\0\u16d1\0\166"+
    "\0\u170c\0\u1747\0\u1782\0\u17bd\0\u1696";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[149];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\2\2\1\3\1\4\1\2\1\5\1\6\1\7\2\3"+
    "\1\10\10\3\1\11\1\12\1\13\1\14\1\15\1\3"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\3\1\32\1\3\1\33"+
    "\1\3\1\34\1\35\1\36\1\3\1\37\1\3\2\2"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\75\0\1\3\1\51\1\0\1\3\2\0\2\3"+
    "\1\0\16\3\11\0\2\3\1\0\13\3\17\0\1\3"+
    "\73\0\1\5\53\0\1\52\17\0\1\6\73\0\1\53"+
    "\65\0\1\3\1\51\1\0\1\3\2\0\2\3\1\0"+
    "\11\3\1\54\4\3\11\0\2\3\1\0\13\3\15\0"+
    "\1\3\1\51\1\0\1\3\2\0\2\3\1\0\13\3"+
    "\1\55\2\3\11\0\2\3\1\0\13\3\15\0\1\3"+
    "\1\51\1\0\1\3\2\0\2\3\1\0\16\3\11\0"+
    "\2\3\1\0\7\3\1\56\3\3\15\0\1\3\1\51"+
    "\1\0\1\3\2\0\2\3\1\0\14\3\1\57\1\3"+
    "\11\0\2\3\1\0\13\3\15\0\1\3\1\51\1\0"+
    "\1\3\2\0\2\3\1\0\16\3\11\0\2\3\1\0"+
    "\7\3\1\60\3\3\46\0\1\61\73\0\1\62\74\0"+
    "\1\63\1\64\72\0\1\65\72\0\1\66\33\0\12\67"+
    "\1\70\60\67\12\71\1\0\26\71\1\72\31\71\2\0"+
    "\1\3\1\51\1\0\1\3\2\0\2\3\1\0\14\3"+
    "\1\73\1\3\11\0\2\3\1\0\13\3\15\0\1\3"+
    "\1\51\1\0\1\3\2\0\2\3\1\0\11\3\1\74"+
    "\4\3\11\0\2\3\1\0\1\3\1\75\11\3\15\0"+
    "\1\3\1\51\1\0\1\3\2\0\2\3\1\0\13\3"+
    "\1\76\2\3\11\0\2\3\1\0\2\3\1\77\10\3"+
    "\15\0\1\3\1\51\1\0\1\3\2\0\2\3\1\0"+
    "\16\3\11\0\2\3\1\0\4\3\1\100\6\3\15\0"+
    "\1\3\1\51\1\0\1\3\2\0\2\3\1\0\16\3"+
    "\11\0\2\3\1\0\4\3\1\101\6\3\15\0\1\3"+
    "\1\51\1\0\1\3\2\0\2\3\1\0\16\3\11\0"+
    "\2\3\1\0\2\3\1\102\10\3\15\0\1\3\1\51"+
    "\1\0\1\3\2\0\2\3\1\0\14\3\1\103\1\3"+
    "\11\0\2\3\1\0\13\3\13\0\1\104\2\105\1\106"+
    "\1\104\1\105\1\104\3\105\1\0\16\105\1\104\3\105"+
    "\3\104\1\105\1\104\2\105\1\104\13\105\1\104\1\105"+
    "\1\107\10\104\5\0\1\110\75\0\1\111\4\0\1\112"+
    "\57\0\1\3\1\51\1\0\1\3\2\0\2\3\1\0"+
    "\12\3\1\113\3\3\11\0\2\3\1\0\13\3\15\0"+
    "\1\3\1\51\1\0\1\3\2\0\2\3\1\0\15\3"+
    "\1\114\11\0\2\3\1\0\13\3\15\0\1\3\1\51"+
    "\1\0\1\3\2\0\2\3\1\0\16\3\11\0\2\3"+
    "\1\0\1\3\1\115\11\3\15\0\1\3\1\51\1\0"+
    "\1\3\2\0\2\3\1\0\15\3\1\116\11\0\2\3"+
    "\1\0\13\3\13\0\12\71\1\0\26\71\1\117\43\71"+
    "\1\0\26\71\1\120\31\71\2\0\1\3\1\51\1\0"+
    "\1\3\2\0\2\3\1\0\16\3\11\0\1\3\1\121"+
    "\1\0\13\3\15\0\1\3\1\51\1\0\1\3\2\0"+
    "\2\3\1\0\15\3\1\122\11\0\2\3\1\0\13\3"+
    "\15\0\1\3\1\51\1\0\1\3\2\0\2\3\1\0"+
    "\14\3\1\123\1\3\11\0\2\3\1\0\13\3\15\0"+
    "\1\3\1\51\1\0\1\3\2\0\2\3\1\0\13\3"+
    "\1\124\2\3\11\0\2\3\1\0\13\3\15\0\1\3"+
    "\1\51\1\0\1\3\2\0\2\3\1\0\10\3\1\125"+
    "\5\3\11\0\2\3\1\0\13\3\15\0\1\3\1\51"+
    "\1\0\1\3\2\0\2\3\1\0\16\3\11\0\1\3"+
    "\1\126\1\0\13\3\15\0\1\3\1\51\1\0\1\3"+
    "\2\0\2\3\1\0\16\3\11\0\1\3\1\127\1\0"+
    "\10\3\1\130\2\3\15\0\1\3\1\51\1\0\1\3"+
    "\2\0\2\3\1\0\16\3\11\0\2\3\1\0\7\3"+
    "\1\131\3\3\75\0\1\132\11\0\2\105\1\133\1\0"+
    "\1\105\1\0\3\105\1\0\16\105\1\0\3\105\3\0"+
    "\1\105\1\0\2\105\1\0\13\105\1\0\1\105\1\132"+
    "\14\0\1\105\55\0\1\132\21\0\1\134\100\0\1\135"+
    "\55\0\1\3\1\51\1\0\1\3\2\0\2\3\1\0"+
    "\16\3\11\0\2\3\1\0\1\136\12\3\13\0\12\137"+
    "\1\140\26\137\1\141\31\137\2\0\1\3\1\51\1\0"+
    "\1\3\2\0\2\3\1\0\11\3\1\142\4\3\11\0"+
    "\2\3\1\0\13\3\15\0\1\3\1\51\1\0\1\3"+
    "\2\0\2\3\1\0\16\3\11\0\1\3\1\143\1\0"+
    "\13\3\15\0\1\3\1\51\1\0\1\3\2\0\2\3"+
    "\1\0\10\3\1\144\5\3\11\0\2\3\1\0\13\3"+
    "\15\0\1\3\1\51\1\0\1\3\2\0\2\3\1\0"+
    "\14\3\1\145\1\3\11\0\2\3\1\0\13\3\15\0"+
    "\1\3\1\51\1\0\1\3\2\0\2\3\1\0\16\3"+
    "\11\0\2\3\1\0\2\3\1\146\10\3\15\0\1\3"+
    "\1\51\1\0\1\3\2\0\2\3\1\0\16\3\11\0"+
    "\2\3\1\0\1\3\1\147\11\3\15\0\1\3\1\51"+
    "\1\0\1\3\2\0\2\3\1\0\16\3\11\0\2\3"+
    "\1\0\7\3\1\150\3\3\15\0\1\3\1\51\1\0"+
    "\1\3\2\0\2\3\1\0\10\3\1\151\5\3\11\0"+
    "\2\3\1\0\13\3\17\0\1\105\66\0\7\134\1\152"+
    "\63\134\20\0\1\153\54\0\1\3\1\51\1\0\1\3"+
    "\2\0\2\3\1\0\14\3\1\154\1\3\11\0\2\3"+
    "\1\0\13\3\13\0\41\140\1\155\31\140\12\137\1\140"+
    "\26\137\1\156\31\137\2\0\1\3\1\51\1\0\1\3"+
    "\2\0\2\3\1\0\15\3\1\157\11\0\2\3\1\0"+
    "\13\3\15\0\1\3\1\51\1\0\1\3\2\0\2\3"+
    "\1\0\11\3\1\160\4\3\11\0\2\3\1\0\13\3"+
    "\15\0\1\3\1\51\1\0\1\3\2\0\2\3\1\0"+
    "\15\3\1\161\11\0\2\3\1\0\13\3\15\0\1\3"+
    "\1\51\1\0\1\3\2\0\2\3\1\0\16\3\11\0"+
    "\1\3\1\162\1\0\13\3\15\0\1\3\1\51\1\0"+
    "\1\3\2\0\2\3\1\0\16\3\11\0\2\3\1\0"+
    "\7\3\1\163\3\3\15\0\1\3\1\51\1\0\1\3"+
    "\2\0\2\3\1\0\16\3\11\0\2\3\1\0\12\3"+
    "\1\164\13\0\7\134\1\165\63\134\21\0\1\166\53\0"+
    "\1\3\1\51\1\0\1\3\2\0\2\3\1\0\11\3"+
    "\1\167\4\3\11\0\2\3\1\0\13\3\13\0\41\140"+
    "\1\170\31\140\12\137\1\140\26\137\1\171\31\137\2\0"+
    "\1\3\1\51\1\0\1\3\2\0\2\3\1\0\16\3"+
    "\11\0\2\3\1\172\13\3\15\0\1\3\1\51\1\0"+
    "\1\3\2\0\2\3\1\0\16\3\11\0\1\173\1\3"+
    "\1\0\13\3\15\0\1\3\1\51\1\0\1\3\2\0"+
    "\2\3\1\0\16\3\11\0\1\3\1\174\1\0\13\3"+
    "\15\0\1\3\1\51\1\0\1\3\2\0\2\3\1\0"+
    "\11\3\1\175\4\3\11\0\2\3\1\0\13\3\15\0"+
    "\1\3\1\51\1\0\1\3\2\0\2\3\1\0\16\3"+
    "\11\0\2\3\1\0\13\3\1\176\12\0\7\134\1\165"+
    "\3\134\1\177\57\134\17\0\1\200\53\0\41\140\1\201"+
    "\31\140\2\0\1\3\1\51\1\0\1\3\2\0\2\3"+
    "\1\0\16\3\11\0\2\3\1\0\1\202\12\3\15\0"+
    "\1\3\1\51\1\0\1\3\2\0\2\3\1\0\11\3"+
    "\1\203\4\3\11\0\2\3\1\0\13\3\15\0\1\3"+
    "\1\51\1\0\1\3\2\0\2\3\1\0\16\3\11\0"+
    "\1\204\1\3\1\0\13\3\13\0\7\134\1\152\4\134"+
    "\1\205\56\134\14\0\1\206\60\0\1\3\1\51\1\0"+
    "\1\3\2\0\2\3\1\0\15\3\1\207\11\0\2\3"+
    "\1\0\13\3\15\0\1\3\1\51\1\0\1\3\2\0"+
    "\2\3\1\0\16\3\11\0\1\210\1\3\1\0\13\3"+
    "\15\0\1\3\1\51\1\0\1\3\2\0\2\3\1\0"+
    "\16\3\11\0\2\3\1\0\1\211\12\3\13\0\7\134"+
    "\1\152\1\212\62\134\22\0\1\213\52\0\1\3\1\51"+
    "\1\0\1\3\2\0\2\3\1\0\16\3\11\0\2\3"+
    "\1\0\1\214\12\3\15\0\1\3\1\51\1\0\1\3"+
    "\2\0\2\3\1\0\15\3\1\215\11\0\2\3\1\0"+
    "\13\3\13\0\7\134\1\152\4\134\1\216\56\134\14\0"+
    "\1\217\60\0\1\3\1\51\1\0\1\3\2\0\2\3"+
    "\1\0\15\3\1\220\11\0\2\3\1\0\13\3\13\0"+
    "\7\216\1\221\63\216\73\217\7\216\1\222\72\216\1\222"+
    "\5\216\1\223\64\216\1\221\6\216\1\224\63\216\1\221"+
    "\2\216\1\225\60\216";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6136];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\1\11\5\1\2\11\11\1\1\11"+
    "\2\1\1\11\4\1\10\11\3\0\5\1\6\11\1\0"+
    "\1\11\1\0\12\1\3\0\2\1\2\0\17\1\1\11"+
    "\3\0\1\1\2\0\11\1\2\0\1\1\1\0\7\1"+
    "\2\0\1\1\1\0\1\1\1\11\3\1\1\11\2\0"+
    "\4\1\2\0\3\1\2\0\2\1\1\0\2\1\3\0"+
    "\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[149];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    //coidgo de usuario en sintaxis java
    //public ArrayList<ErrorG> listaErrores = new  ArrayList<>();



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalizadorLexicoPY(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public AnalizadorLexicoPY(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 43: 
          { System.out.println("Comentario: "+yytext()); return new Symbol(SimbolosPY.COMENTARIO_VARIOS , yycolumn, yyline, yytext());
          }
        case 51: break;
        case 31: 
          { System.out.println(yytext()); return new Symbol(SimbolosPY.TEXTO , yycolumn, yyline, yytext());
          }
        case 52: break;
        case 1: 
          { System.out.println("error Lexico: "+"Columna: "+yycolumn+1+" linea: "+ yyline+1 + "Token: "+yytext());
                                    /*ErrorG e = new ErrorG(yyline+1, yycolumn+1,yytext(),"Lexico","Error Lexico token: " + yytext()+"   Linea: " + (yyline+1) + " ,    Columna: " + (yycolumn+1));
                                    listaErrores.add(e);*/
          }
        case 53: break;
        case 24: 
          { System.out.println("EXPONENTE"); return new Symbol(SimbolosPY.POT , yycolumn, yyline, yytext());
          }
        case 54: break;
        case 47: 
          { System.out.println("charinput"); return new Symbol(SimbolosPY.CHARINPUT , yycolumn, yyline, yytext());
          }
        case 55: break;
        case 17: 
          { System.out.println("CHORCHETE ABRE"); return new Symbol(SimbolosPY.CORCHETE_A , yycolumn, yyline, yytext());
          }
        case 56: break;
        case 42: 
          { System.out.println(yytext()); return new Symbol(SimbolosPY.RETURN , yycolumn, yyline, yytext());
          }
        case 57: break;
        case 26: 
          { System.out.println("DIFERENTE"); return new Symbol(SimbolosPY.DIFERENTE , yycolumn, yyline, yytext());
          }
        case 58: break;
        case 30: 
          { System.out.println("Comentario: "+yytext()); return new Symbol(SimbolosPY.COMENTARIO_SIMPLE , yycolumn, yyline, yytext());
          }
        case 59: break;
        case 13: 
          { System.out.println("PARENTESIS_A"); return new Symbol(SimbolosPY.PARENTESIS_A , yycolumn, yyline, yytext());
          }
        case 60: break;
        case 19: 
          { System.out.println("LLAVES ABRE"); return new Symbol(SimbolosPY.LLAVES_A , yycolumn, yyline, yytext());
          }
        case 61: break;
        case 10: 
          { System.out.println("MENOR_QUE"); return new Symbol(SimbolosPY.MENOR_QUE , yycolumn, yyline, yytext());
          }
        case 62: break;
        case 6: 
          { System.out.println("MAS"); return new Symbol(SimbolosPY.MAS , yycolumn, yyline, yytext());
          }
        case 63: break;
        case 23: 
          { System.out.println(yytext()); return new Symbol(SimbolosPY.OR , yycolumn, yyline, yytext());
          }
        case 64: break;
        case 41: 
          { System.out.println("while"); return new Symbol(SimbolosPY.WHILE , yycolumn, yyline, yytext());
          }
        case 65: break;
        case 32: 
          { System.out.println("in"); return new Symbol(SimbolosPY.IN , yycolumn, yyline, yytext());
          }
        case 66: break;
        case 46: 
          { System.out.println("intinput"); return new Symbol(SimbolosPY.INTINPUT , yycolumn, yyline, yytext());
          }
        case 67: break;
        case 35: 
          { System.out.println(yytext()); return new Symbol(SimbolosPY.AND , yycolumn, yyline, yytext());
          }
        case 68: break;
        case 27: 
          { System.out.println("MENOR_IGUAL"); return new Symbol(SimbolosPY.MENOR_IGUAL , yycolumn, yyline, yytext());
          }
        case 69: break;
        case 20: 
          { System.out.println("LLAVES CIEERRE"); return new Symbol(SimbolosPY.LLAVES_C , yycolumn, yyline, yytext());
          }
        case 70: break;
        case 29: 
          { System.out.println("IGUAL_IGUAL"); return new Symbol(SimbolosPY.IGUAL_IGUAL , yycolumn, yyline, yytext());
          }
        case 71: break;
        case 8: 
          { System.out.println("*"); return new Symbol(SimbolosPY.POR , yycolumn, yyline, yytext());
          }
        case 72: break;
        case 21: 
          { System.out.println("COMA"); return new Symbol(SimbolosPY.COMA , yycolumn, yyline, yytext());
          }
        case 73: break;
        case 15: 
          { System.out.println("TAB"); return new Symbol(SimbolosPY.TAB , yycolumn, yyline, yytext());
          }
        case 74: break;
        case 50: 
          { System.out.println(yytext()); return new Symbol(SimbolosPY.SEPARADOR_PY , yycolumn, yyline, yytext());
          }
        case 75: break;
        case 48: 
          { System.out.println(yytext()); return new Symbol(SimbolosPY.SEPARADOR_PROGRAMA , yycolumn, yyline, yytext());
          }
        case 76: break;
        case 16: 
          { System.out.println("dos puntos"); return new Symbol(SimbolosPY.DOS_PUNTOS , yycolumn, yyline, yytext());
          }
        case 77: break;
        case 45: 
          { System.out.println(yytext()); return new Symbol(SimbolosPY.BREAK , yycolumn, yyline, yytext());
          }
        case 78: break;
        case 22: 
          { System.out.println("PARENTESIS_C"); return new Symbol(SimbolosPY.PARENTESIS_C , yycolumn, yyline, yytext());
          }
        case 79: break;
        case 33: 
          { System.out.println(yytext()); return new Symbol(SimbolosPY.IF , yycolumn, yyline, yytext());
          }
        case 80: break;
        case 34: 
          { System.out.println(yytext()); return new Symbol(SimbolosPY.VALOR , yycolumn, yyline, yytext());
          }
        case 81: break;
        case 44: 
          { System.out.println("Mensaje: "+yytext()); return new Symbol(SimbolosPY.PRINT , yycolumn, yyline, yytext());
          }
        case 82: break;
        case 36: 
          { System.out.println(yytext()); return new Symbol(SimbolosPY.NOT , yycolumn, yyline, yytext());
          }
        case 83: break;
        case 2: 
          { System.out.println("id: "+yytext()); return new Symbol(SimbolosPY.IDENTIFICADOR , yycolumn, yyline, yytext());
          }
        case 84: break;
        case 40: 
          { System.out.println(yytext()); return new Symbol(SimbolosPY.ELSE , yycolumn, yyline, yytext());
          }
        case 85: break;
        case 9: 
          { System.out.println("DIV"); return new Symbol(SimbolosPY.DIV , yycolumn, yyline, yytext());
          }
        case 86: break;
        case 7: 
          { System.out.println("MENOS"); return new Symbol(SimbolosPY.MENOS , yycolumn, yyline, yytext());
          }
        case 87: break;
        case 25: 
          { System.out.println("DIV_ENTERA"); return new Symbol(SimbolosPY.DIV_ENTERA , yycolumn, yyline, yytext());
          }
        case 88: break;
        case 37: 
          { System.out.println(yytext()); return new Symbol(SimbolosPY.DEF, yycolumn, yyline, yytext());
          }
        case 89: break;
        case 14: 
          { System.out.println("_"); return new Symbol(SimbolosPY.GUION_BAJO , yycolumn, yyline, yytext());
          }
        case 90: break;
        case 49: 
          { System.out.println("floarinput"); return new Symbol(SimbolosPY.FLOATINPUT , yycolumn, yyline, yytext());
          }
        case 91: break;
        case 18: 
          { System.out.println("CORCHE CIERRE"); return new Symbol(SimbolosPY.CORCHETE_C , yycolumn, yyline, yytext());
          }
        case 92: break;
        case 12: 
          { System.out.println("IGUAL"); return new Symbol(SimbolosPY.IGUAL , yycolumn, yyline, yytext());
          }
        case 93: break;
        case 4: 
          { /*Ignore*/
          }
        case 94: break;
        case 39: 
          { System.out.println(yytext()); return new Symbol(SimbolosPY.ELSE_IF , yycolumn, yyline, yytext());
          }
        case 95: break;
        case 3: 
          { System.out.println("NUMERO: "+yytext()); return new Symbol(SimbolosPY.NUMERO , yycolumn, yyline, yytext());
          }
        case 96: break;
        case 38: 
          { System.out.println("for"); return new Symbol(SimbolosPY.FOR , yycolumn, yyline, yytext());
          }
        case 97: break;
        case 5: 
          { System.out.println("SALTO"); return new Symbol(SimbolosPY.SALTO , yycolumn, yyline, yytext());
          }
        case 98: break;
        case 28: 
          { System.out.println("MAYOR_IGUAL"); return new Symbol(SimbolosPY.MAYOR_IGUAL , yycolumn, yyline, yytext());
          }
        case 99: break;
        case 11: 
          { System.out.println("MAYOR_QUE"); return new Symbol(SimbolosPY.MAYOR_QUE , yycolumn, yyline, yytext());
          }
        case 100: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(SimbolosPY.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
