
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Oct 13 14:06:06 CST 2020
//----------------------------------------------------

package analisis.py;

/** CUP generated class containing symbol constants. */
public class SimbolosPY {
  /* terminals */
  public static final int NUMERO = 37;
  public static final int POT = 9;
  public static final int POR = 10;
  public static final int LLAVES_C = 47;
  public static final int LLAVES_A = 46;
  public static final int COMENTARIO_VARIOS = 21;
  public static final int DIFERENTE = 19;
  public static final int DOS_PUNTOS = 43;
  public static final int CORCHETE_C = 45;
  public static final int CORCHETE_A = 44;
  public static final int FOR = 26;
  public static final int IDENTIFICADOR = 36;
  public static final int NOT = 6;
  public static final int AND = 4;
  public static final int RANGE = 51;
  public static final int IGUAL = 42;
  public static final int IN = 27;
  public static final int OR = 5;
  public static final int DIV_ENTERO = 17;
  public static final int TAB = 41;
  public static final int DIV = 12;
  public static final int INTINPUT = 23;
  public static final int IF = 30;
  public static final int ELSE_IF = 32;
  public static final int IGUAL_IGUAL = 18;
  public static final int DECIMAL = 52;
  public static final int EOF = 0;
  public static final int RETURN = 35;
  public static final int SEPARADOR_PROGRAMA = 3;
  public static final int DIV_ENTERA = 11;
  public static final int error = 1;
  public static final int COMA = 48;
  public static final int MENOS = 8;
  public static final int MAYOR_QUE = 14;
  public static final int BREAK = 33;
  public static final int COMENTARIO_SIMPLE = 20;
  public static final int GUION_BAJO = 28;
  public static final int VALOR = 38;
  public static final int ELSE = 31;
  public static final int PARENTESIS_C = 50;
  public static final int FLOATINPUT = 24;
  public static final int WHILE = 29;
  public static final int PARENTESIS_A = 49;
  public static final int MAYOR_IGUAL = 16;
  public static final int SEPARADOR_PY = 2;
  public static final int CHARINPUT = 25;
  public static final int DEF = 34;
  public static final int MENOR_QUE = 13;
  public static final int TEXTO = 39;
  public static final int MENOR_IGUAL = 15;
  public static final int SALTO = 40;
  public static final int PRINT = 22;
  public static final int MAS = 7;
}

