
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Sep 20 20:36:54 CST 2020
//----------------------------------------------------

package analisis.vb;

/** CUP generated class containing symbol constants. */
public class SimbolosVB {
  /* terminals */
  public static final int AS = 51;
  public static final int IDENTIFICADOR = 50;
  public static final int MENOR_IGUAL = 19;
  public static final int MENOR_QUE = 17;
  public static final int WEND = 71;
  public static final int UNTIL = 38;
  public static final int SEPARADOR_VB = 2;
  public static final int NEXT = 34;
  public static final int LIKE = 24;
  public static final int DIFERENTE = 21;
  public static final int POT = 16;
  public static final int POR = 13;
  public static final int INTEGER = 6;
  public static final int NUMERO = 54;
  public static final int MAYOR_QUE = 18;
  public static final int SUB = 70;
  public static final int CONSOLE_WRT = 27;
  public static final int LOOP = 41;
  public static final int NOT = 65;
  public static final int COMENTARIO = 25;
  public static final int CORCHETE_C = 56;
  public static final int CORCHETE_A = 55;
  public static final int THEN = 43;
  public static final int LLAVES_C = 58;
  public static final int LLAVES_A = 57;
  public static final int SELECT = 46;
  public static final int COMA = 59;
  public static final int CHART = 8;
  public static final int SEPARADOR_PROGRAMA = 5;
  public static final int DECIMAL_R = 7;
  public static final int IGUAL = 52;
  public static final int WHILE = 35;
  public static final int MODULE = 69;
  public static final int DECIMAL = 53;
  public static final int ELSE_IF = 45;
  public static final int DO = 37;
  public static final int FOR = 31;
  public static final int DIV = 14;
  public static final int PUBLIC = 48;
  public static final int RETURN = 68;
  public static final int SEPARADOR_JAVA = 3;
  public static final int ELSE = 44;
  public static final int MENOS = 12;
  public static final int FLOATINPUT = 29;
  public static final int MAS = 11;
  public static final int AND_RESRV = 62;
  public static final int DIM = 49;
  public static final int SALTO = 10;
  public static final int PARENTESIS_C = 61;
  public static final int PARENTESIS_A = 60;
  public static final int EOF = 0;
  public static final int FUNCTION = 67;
  public static final int CHARINPUT = 30;
  public static final int ISNOT = 23;
  public static final int IS = 22;
  public static final int DIV_ENTERO = 15;
  public static final int MSG = 26;
  public static final int OR = 64;
  public static final int error = 1;
  public static final int EXIT = 40;
  public static final int CONTINUE = 39;
  public static final int IF = 42;
  public static final int END = 36;
  public static final int INTINPUT = 28;
  public static final int VALOR = 9;
  public static final int CASE = 47;
  public static final int STEP = 33;
  public static final int AND = 63;
  public static final int TO = 32;
  public static final int MAYOR_IGUAL = 20;
  public static final int XOR = 66;
  public static final int SEPARADOR_PY = 4;
}

