/* The following code was generated by JFlex 1.4.3 on 27/09/20 06:19 PM */

package analisis.cpp;
import java_cup.runtime.*;
import java.util.ArrayList;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 27/09/20 06:19 PM from the specification file
 * <tt>LexicoCPP.jflex</tt>
 */
public class AnalizadorLexicoCPP implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  5,  0,  9,  0,  0,  5,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     5, 38, 56, 18,  0,  6, 36, 55, 31, 33, 41, 39, 61, 40, 54, 42, 
     4,  4,  4,  4,  4,  4,  4,  4,  4,  4, 51, 50, 43, 45, 44,  0, 
     0, 11,  8,  1,  1,  1,  1, 16,  1,  1, 10,  1,  1, 17,  1, 15, 
    12,  1, 14,  1,  1,  1,  7,  1,  1, 13,  1, 57,  0, 58,  0, 53, 
     0, 29, 48, 21, 24, 25, 30, 34, 35, 19,  1, 49, 22,  1, 20, 26, 
    46,  1, 32, 27, 28, 23, 52, 47,  1,  1,  1, 59, 37, 60,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\4\1\5\1\1"+
    "\6\2\1\6\1\2\1\7\1\2\1\10\1\1\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\3\2"+
    "\1\21\1\22\1\2\1\23\2\1\1\24\1\25\1\26"+
    "\1\27\1\30\4\0\1\2\1\31\5\2\1\32\7\2"+
    "\1\33\1\34\1\35\1\36\1\37\2\0\1\40\1\41"+
    "\1\42\4\2\1\0\1\43\1\0\1\44\1\45\2\0"+
    "\1\46\11\2\1\47\2\2\1\0\1\50\4\2\2\0"+
    "\2\2\1\51\1\52\1\2\1\53\5\2\1\54\3\2"+
    "\1\55\2\0\1\2\1\56\3\2\1\57\3\2\1\60"+
    "\1\2\2\0\2\2\1\61\1\62\1\63\1\0\1\2"+
    "\1\64\3\0\1\2\1\65\1\66\1\0\1\67\1\70"+
    "\1\71\17\0\1\72";

  private static int [] zzUnpackAction() {
    int [] result = new int[168];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\76\0\174\0\272\0\370\0\u0136\0\u0174\0\u01b2"+
    "\0\u01f0\0\u022e\0\u026c\0\u02aa\0\u02e8\0\u0326\0\76\0\u0364"+
    "\0\76\0\u03a2\0\u03e0\0\u041e\0\u045c\0\u049a\0\u04d8\0\76"+
    "\0\u0516\0\u0554\0\u0592\0\u05d0\0\u060e\0\u064c\0\u068a\0\76"+
    "\0\76\0\u06c8\0\76\0\u0706\0\u0744\0\76\0\76\0\76"+
    "\0\76\0\76\0\272\0\u0782\0\u07c0\0\u07fe\0\u083c\0\174"+
    "\0\u087a\0\u08b8\0\u08f6\0\u0934\0\u0972\0\174\0\u09b0\0\u09ee"+
    "\0\u0a2c\0\u0a6a\0\u0aa8\0\u0ae6\0\u0b24\0\76\0\76\0\76"+
    "\0\76\0\76\0\u0b62\0\u0ba0\0\76\0\76\0\76\0\u0bde"+
    "\0\u0c1c\0\u0c5a\0\u0c98\0\u0706\0\u0706\0\u0744\0\u0744\0\u0782"+
    "\0\u0cd6\0\u0d14\0\174\0\u0d52\0\u0d90\0\u0dce\0\u0e0c\0\u0e4a"+
    "\0\u0e88\0\u0ec6\0\u0f04\0\u0f42\0\174\0\u0f80\0\u0fbe\0\u0ffc"+
    "\0\76\0\u103a\0\u1078\0\u10b6\0\u10f4\0\u1132\0\u1170\0\u11ae"+
    "\0\u11ec\0\174\0\174\0\u122a\0\174\0\u1268\0\u12a6\0\u12e4"+
    "\0\u1322\0\u1360\0\u0b62\0\u139e\0\u13dc\0\u141a\0\174\0\u1458"+
    "\0\u1496\0\u14d4\0\174\0\u1512\0\u1550\0\u158e\0\174\0\u15cc"+
    "\0\u160a\0\u1648\0\174\0\u1686\0\u16c4\0\u1702\0\u1740\0\u177e"+
    "\0\76\0\174\0\174\0\u17bc\0\u17fa\0\76\0\u1838\0\u1876"+
    "\0\u18b4\0\u18f2\0\76\0\76\0\u1930\0\76\0\76\0\76"+
    "\0\u196e\0\u19ac\0\u19ea\0\u1a28\0\u1a66\0\u1aa4\0\u1ae2\0\u1b20"+
    "\0\u1b5e\0\u1b9c\0\u1bda\0\u1c18\0\u1c56\0\u1c94\0\u1cd2\0\u1aa4";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[168];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\5\1\6\1\7\2\3"+
    "\1\6\10\3\1\10\1\11\1\3\1\12\2\3\1\13"+
    "\1\14\1\3\1\15\2\3\1\16\1\17\1\20\1\21"+
    "\1\22\1\3\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\3"+
    "\1\40\1\41\1\42\1\2\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\77\0\1\3\1\53\1\0"+
    "\1\3\2\0\2\3\1\0\10\3\1\0\14\3\1\0"+
    "\1\3\1\0\2\3\12\0\4\3\2\0\2\3\13\0"+
    "\1\3\76\0\1\5\61\0\1\54\14\0\1\6\3\0"+
    "\1\6\72\0\1\55\112\0\1\56\53\0\1\3\1\53"+
    "\1\0\1\3\2\0\2\3\1\0\10\3\1\0\1\3"+
    "\1\57\11\3\1\60\1\0\1\3\1\0\2\3\12\0"+
    "\4\3\2\0\2\3\11\0\1\3\1\53\1\0\1\3"+
    "\2\0\2\3\1\0\10\3\1\0\3\3\1\61\3\3"+
    "\1\62\2\3\1\63\1\3\1\0\1\3\1\0\1\3"+
    "\1\64\12\0\4\3\2\0\2\3\11\0\1\3\1\53"+
    "\1\0\1\3\2\0\2\3\1\0\10\3\1\0\6\3"+
    "\1\65\1\66\4\3\1\0\1\3\1\0\2\3\12\0"+
    "\4\3\2\0\2\3\11\0\1\3\1\53\1\0\1\3"+
    "\2\0\2\3\1\0\10\3\1\0\3\3\1\67\10\3"+
    "\1\0\1\3\1\0\2\3\12\0\4\3\2\0\2\3"+
    "\11\0\1\3\1\53\1\0\1\3\2\0\2\3\1\0"+
    "\10\3\1\0\2\3\1\70\11\3\1\0\1\3\1\0"+
    "\2\3\12\0\1\3\1\71\2\3\2\0\2\3\11\0"+
    "\1\3\1\53\1\0\1\3\2\0\2\3\1\0\10\3"+
    "\1\0\3\3\1\72\3\3\1\73\4\3\1\0\1\3"+
    "\1\0\2\3\12\0\4\3\2\0\2\3\11\0\1\3"+
    "\1\53\1\0\1\3\2\0\2\3\1\0\10\3\1\0"+
    "\6\3\1\74\5\3\1\0\1\3\1\0\2\3\12\0"+
    "\4\3\2\0\2\3\11\0\1\3\1\53\1\0\1\3"+
    "\2\0\2\3\1\0\10\3\1\0\6\3\1\75\5\3"+
    "\1\0\1\3\1\0\2\3\12\0\4\3\2\0\2\3"+
    "\54\0\1\76\76\0\1\77\105\0\1\100\67\0\1\101"+
    "\32\0\1\5\43\0\1\102\76\0\1\103\1\104\100\0"+
    "\1\105\75\0\1\106\75\0\1\107\21\0\1\3\1\53"+
    "\1\0\1\3\2\0\2\3\1\0\10\3\1\0\14\3"+
    "\1\0\1\110\1\0\2\3\12\0\4\3\2\0\2\3"+
    "\11\0\1\3\1\53\1\0\1\3\2\0\2\3\1\0"+
    "\10\3\1\0\14\3\1\0\1\3\1\0\1\3\1\111"+
    "\12\0\4\3\2\0\2\3\11\0\1\3\1\53\1\0"+
    "\1\3\2\0\2\3\1\0\10\3\1\0\14\3\1\0"+
    "\1\112\1\0\2\3\12\0\4\3\2\0\2\3\11\0"+
    "\1\3\1\53\1\0\1\3\2\0\2\3\1\0\10\3"+
    "\1\0\7\3\1\113\4\3\1\0\1\3\1\0\2\3"+
    "\12\0\4\3\2\0\2\3\10\0\11\114\1\0\55\114"+
    "\1\115\6\114\11\116\1\0\56\116\1\117\5\116\4\0"+
    "\1\120\100\0\1\121\112\0\1\122\52\0\1\3\1\53"+
    "\1\0\1\3\2\0\2\3\1\0\10\3\1\0\11\3"+
    "\1\123\2\3\1\0\1\3\1\0\2\3\12\0\4\3"+
    "\2\0\2\3\11\0\1\3\1\53\1\0\1\3\2\0"+
    "\2\3\1\0\10\3\1\0\14\3\1\0\1\124\1\0"+
    "\2\3\12\0\4\3\2\0\2\3\11\0\1\3\1\53"+
    "\1\0\1\3\2\0\2\3\1\0\10\3\1\0\1\3"+
    "\1\125\12\3\1\0\1\3\1\0\2\3\12\0\4\3"+
    "\2\0\2\3\11\0\1\3\1\53\1\0\1\3\2\0"+
    "\2\3\1\0\10\3\1\0\10\3\1\126\3\3\1\0"+
    "\1\3\1\0\2\3\12\0\4\3\2\0\2\3\11\0"+
    "\1\3\1\53\1\0\1\3\2\0\2\3\1\0\10\3"+
    "\1\0\12\3\1\127\1\3\1\0\1\3\1\0\2\3"+
    "\12\0\4\3\2\0\2\3\11\0\1\3\1\53\1\0"+
    "\1\3\2\0\2\3\1\0\10\3\1\0\13\3\1\130"+
    "\1\0\1\3\1\0\2\3\12\0\4\3\2\0\2\3"+
    "\11\0\1\3\1\53\1\0\1\3\2\0\2\3\1\0"+
    "\10\3\1\0\10\3\1\131\3\3\1\0\1\3\1\0"+
    "\2\3\12\0\4\3\2\0\2\3\11\0\1\3\1\53"+
    "\1\0\1\3\2\0\2\3\1\0\10\3\1\0\12\3"+
    "\1\132\1\3\1\0\1\3\1\0\2\3\12\0\4\3"+
    "\2\0\2\3\11\0\1\3\1\53\1\0\1\3\2\0"+
    "\2\3\1\0\10\3\1\0\1\133\13\3\1\0\1\3"+
    "\1\0\2\3\12\0\4\3\2\0\2\3\11\0\1\3"+
    "\1\53\1\0\1\3\2\0\2\3\1\0\10\3\1\0"+
    "\7\3\1\134\4\3\1\0\1\3\1\0\2\3\12\0"+
    "\4\3\2\0\2\3\11\0\1\3\1\53\1\0\1\3"+
    "\2\0\2\3\1\0\10\3\1\0\14\3\1\0\1\135"+
    "\1\0\2\3\12\0\4\3\2\0\2\3\11\0\1\3"+
    "\1\53\1\0\1\3\2\0\2\3\1\0\10\3\1\0"+
    "\11\3\1\136\2\3\1\0\1\3\1\0\2\3\12\0"+
    "\4\3\2\0\2\3\11\0\1\3\1\53\1\0\1\3"+
    "\2\0\2\3\1\0\10\3\1\0\11\3\1\137\2\3"+
    "\1\0\1\3\1\0\2\3\12\0\4\3\2\0\2\3"+
    "\10\0\51\103\1\140\24\103\11\104\1\141\64\104\1\0"+
    "\1\3\1\53\1\0\1\3\2\0\2\3\1\0\10\3"+
    "\1\0\1\142\13\3\1\0\1\3\1\0\2\3\12\0"+
    "\4\3\2\0\2\3\11\0\1\3\1\53\1\0\1\3"+
    "\2\0\2\3\1\0\10\3\1\0\1\143\13\3\1\0"+
    "\1\3\1\0\2\3\12\0\4\3\2\0\2\3\11\0"+
    "\1\3\1\53\1\0\1\3\2\0\2\3\1\0\10\3"+
    "\1\0\6\3\1\144\5\3\1\0\1\3\1\0\2\3"+
    "\12\0\4\3\2\0\2\3\11\0\1\3\1\53\1\0"+
    "\1\3\2\0\2\3\1\0\10\3\1\0\1\145\13\3"+
    "\1\0\1\3\1\0\2\3\12\0\4\3\2\0\2\3"+
    "\20\0\1\146\112\0\1\147\51\0\1\3\1\53\1\0"+
    "\1\3\2\0\2\3\1\0\10\3\1\0\10\3\1\150"+
    "\3\3\1\0\1\3\1\0\2\3\12\0\4\3\2\0"+
    "\2\3\11\0\1\3\1\53\1\0\1\3\2\0\2\3"+
    "\1\0\10\3\1\0\10\3\1\151\3\3\1\0\1\3"+
    "\1\0\2\3\12\0\4\3\2\0\2\3\11\0\1\3"+
    "\1\53\1\0\1\3\2\0\2\3\1\0\10\3\1\0"+
    "\6\3\1\152\5\3\1\0\1\3\1\0\2\3\12\0"+
    "\4\3\2\0\2\3\11\0\1\3\1\53\1\0\1\3"+
    "\2\0\2\3\1\0\10\3\1\0\14\3\1\0\1\153"+
    "\1\0\2\3\12\0\4\3\2\0\2\3\11\0\1\3"+
    "\1\53\1\0\1\3\2\0\2\3\1\0\10\3\1\0"+
    "\12\3\1\154\1\3\1\0\1\3\1\0\2\3\12\0"+
    "\4\3\2\0\2\3\11\0\1\3\1\53\1\0\1\3"+
    "\2\0\2\3\1\0\10\3\1\0\6\3\1\155\5\3"+
    "\1\0\1\3\1\0\2\3\12\0\4\3\2\0\2\3"+
    "\11\0\1\3\1\53\1\0\1\3\2\0\2\3\1\0"+
    "\10\3\1\0\1\3\1\156\12\3\1\0\1\3\1\0"+
    "\2\3\12\0\4\3\2\0\2\3\11\0\1\3\1\53"+
    "\1\0\1\3\2\0\2\3\1\0\10\3\1\0\11\3"+
    "\1\157\2\3\1\0\1\3\1\0\2\3\12\0\4\3"+
    "\2\0\2\3\11\0\1\3\1\53\1\0\1\3\2\0"+
    "\2\3\1\0\10\3\1\0\12\3\1\160\1\3\1\0"+
    "\1\3\1\0\2\3\12\0\4\3\2\0\2\3\11\0"+
    "\1\3\1\53\1\0\1\3\2\0\2\3\1\0\10\3"+
    "\1\0\4\3\1\161\7\3\1\0\1\3\1\0\2\3"+
    "\12\0\4\3\2\0\2\3\11\0\1\3\1\53\1\0"+
    "\1\3\2\0\2\3\1\0\10\3\1\0\2\3\1\162"+
    "\11\3\1\0\1\3\1\0\2\3\12\0\4\3\2\0"+
    "\2\3\10\0\51\103\1\140\1\163\23\103\1\0\1\3"+
    "\1\53\1\0\1\3\2\0\2\3\1\0\10\3\1\0"+
    "\1\3\1\164\12\3\1\0\1\3\1\0\2\3\12\0"+
    "\4\3\2\0\2\3\11\0\1\3\1\53\1\0\1\3"+
    "\2\0\2\3\1\0\10\3\1\0\3\3\1\165\10\3"+
    "\1\0\1\3\1\0\2\3\12\0\4\3\2\0\2\3"+
    "\11\0\1\3\1\53\1\0\1\3\2\0\2\3\1\0"+
    "\10\3\1\0\12\3\1\166\1\3\1\0\1\3\1\0"+
    "\2\3\12\0\4\3\2\0\2\3\11\0\1\3\1\53"+
    "\1\0\1\3\2\0\2\3\1\0\10\3\1\0\5\3"+
    "\1\167\6\3\1\0\1\3\1\0\2\3\12\0\4\3"+
    "\2\0\2\3\10\0\6\146\1\170\67\146\26\0\1\171"+
    "\50\0\1\3\1\53\1\0\1\3\2\0\2\3\1\0"+
    "\10\3\1\0\2\3\1\172\11\3\1\0\1\3\1\0"+
    "\2\3\12\0\4\3\2\0\2\3\11\0\1\3\1\53"+
    "\1\0\1\3\2\0\2\3\1\0\10\3\1\0\11\3"+
    "\1\173\2\3\1\0\1\3\1\0\2\3\12\0\4\3"+
    "\2\0\2\3\11\0\1\3\1\53\1\0\1\3\2\0"+
    "\2\3\1\0\10\3\1\0\4\3\1\174\7\3\1\0"+
    "\1\3\1\0\2\3\12\0\4\3\2\0\2\3\11\0"+
    "\1\3\1\53\1\0\1\3\2\0\2\3\1\0\10\3"+
    "\1\0\13\3\1\175\1\0\1\3\1\0\2\3\12\0"+
    "\4\3\2\0\2\3\11\0\1\3\1\53\1\0\1\3"+
    "\2\0\2\3\1\0\10\3\1\0\2\3\1\176\11\3"+
    "\1\0\1\3\1\0\2\3\12\0\4\3\2\0\2\3"+
    "\11\0\1\3\1\53\1\0\1\3\2\0\2\3\1\0"+
    "\10\3\1\0\11\3\1\177\2\3\1\0\1\3\1\0"+
    "\2\3\12\0\4\3\2\0\2\3\11\0\1\3\1\53"+
    "\1\0\1\3\2\0\2\3\1\0\10\3\1\0\14\3"+
    "\1\0\1\200\1\0\2\3\12\0\4\3\2\0\2\3"+
    "\11\0\1\3\1\53\1\0\1\3\2\0\2\3\1\0"+
    "\10\3\1\0\14\3\1\0\1\3\1\0\1\3\1\201"+
    "\12\0\4\3\2\0\2\3\11\0\1\3\1\53\1\0"+
    "\1\3\2\0\2\3\1\0\10\3\1\0\11\3\1\202"+
    "\2\3\1\0\1\3\1\0\2\3\12\0\4\3\2\0"+
    "\2\3\11\0\1\3\1\53\1\0\1\3\2\0\2\3"+
    "\1\0\10\3\1\0\6\3\1\203\5\3\1\0\1\3"+
    "\1\0\2\3\12\0\4\3\2\0\2\3\11\0\1\3"+
    "\1\53\1\0\1\3\2\0\2\3\1\0\10\3\1\0"+
    "\14\3\1\0\1\3\1\0\2\3\12\0\3\3\1\204"+
    "\2\0\2\3\10\0\6\146\1\205\67\146\27\0\1\206"+
    "\47\0\1\3\1\53\1\0\1\3\2\0\2\3\1\0"+
    "\10\3\1\0\14\3\1\0\1\207\1\0\2\3\12\0"+
    "\4\3\2\0\2\3\11\0\1\3\1\53\1\0\1\3"+
    "\2\0\2\3\1\0\10\3\1\0\3\3\1\210\10\3"+
    "\1\0\1\3\1\0\2\3\12\0\4\3\2\0\2\3"+
    "\11\0\1\3\1\53\1\0\1\3\2\0\2\3\1\0"+
    "\10\3\1\0\14\3\1\211\1\3\1\0\2\3\12\0"+
    "\4\3\2\0\2\3\11\0\1\3\1\53\1\0\1\3"+
    "\2\0\2\3\1\0\10\3\1\0\14\3\1\0\1\3"+
    "\1\0\1\3\1\212\12\0\4\3\2\0\2\3\11\0"+
    "\1\3\1\53\1\0\1\3\2\0\2\3\1\0\10\3"+
    "\1\0\1\3\1\213\12\3\1\0\1\3\1\0\2\3"+
    "\12\0\4\3\2\0\2\3\11\0\1\3\1\53\1\0"+
    "\1\3\2\0\2\3\1\0\10\3\1\0\14\3\1\214"+
    "\1\3\1\0\2\3\12\0\4\3\2\0\2\3\11\0"+
    "\1\3\1\53\1\0\1\3\2\0\2\3\1\0\10\3"+
    "\1\0\13\3\1\215\1\0\1\3\1\0\2\3\12\0"+
    "\4\3\2\0\2\3\11\0\1\3\1\53\1\0\1\3"+
    "\2\0\2\3\1\0\10\3\1\0\14\3\1\0\1\3"+
    "\1\0\2\3\12\0\4\3\1\216\1\0\2\3\10\0"+
    "\6\146\1\205\3\146\1\217\63\146\30\0\1\220\46\0"+
    "\1\3\1\53\1\0\1\3\2\0\2\3\1\0\10\3"+
    "\1\0\14\3\1\221\1\3\1\0\2\3\12\0\4\3"+
    "\2\0\2\3\11\0\1\3\1\53\1\0\1\3\2\0"+
    "\2\3\1\0\10\3\1\0\11\3\1\222\2\3\1\0"+
    "\1\3\1\0\2\3\12\0\4\3\2\0\2\3\51\0"+
    "\1\223\35\0\1\3\1\53\1\0\1\3\2\0\2\3"+
    "\1\0\10\3\1\0\14\3\1\224\1\3\1\0\2\3"+
    "\12\0\4\3\2\0\2\3\10\0\6\146\1\170\4\146"+
    "\1\225\62\146\31\0\1\226\105\0\1\227\35\0\1\3"+
    "\1\53\1\0\1\3\2\0\2\3\1\0\10\3\1\0"+
    "\14\3\1\0\1\3\1\0\2\3\12\0\4\3\1\0"+
    "\1\230\2\3\10\0\6\146\1\170\1\231\74\146\1\170"+
    "\4\146\1\232\62\146\6\232\1\233\75\232\1\234\75\232"+
    "\1\234\5\232\1\235\67\232\1\233\6\232\1\236\60\232"+
    "\6\236\1\237\75\236\1\240\75\236\1\240\5\236\1\241"+
    "\67\236\1\237\7\236\1\242\65\236\1\237\10\236\1\243"+
    "\64\236\1\237\11\236\1\244\63\236\1\237\7\236\1\245"+
    "\65\236\1\237\4\236\1\246\70\236\1\237\12\236\1\247"+
    "\62\236\1\237\4\236\1\250\62\236";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7440];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\14\1\1\11\1\1\1\11\6\1\1\11"+
    "\7\1\2\11\1\1\1\11\2\1\5\11\4\0\17\1"+
    "\5\11\2\0\3\11\4\1\1\0\1\1\1\0\2\1"+
    "\2\0\15\1\1\0\1\11\4\1\2\0\20\1\2\0"+
    "\13\1\2\0\2\1\1\11\2\1\1\0\1\1\1\11"+
    "\3\0\1\1\2\11\1\0\3\11\17\0\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[168];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    //coidgo de usuario en sintaxis java
    //public ArrayList<ErrorG> listaErrores = new  ArrayList<>();



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalizadorLexicoCPP(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public AnalizadorLexicoCPP(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { System.out.println("error Lexico: "+"Columna: "+yycolumn+1+" linea: "+ yyline+1 + "Token: "+yytext());
                                    /*ErrorG e = new ErrorG(yyline+1, yycolumn+1,yytext(),"Lexico","Error Lexico token: " + yytext()+"   Linea: " + (yyline+1) + " ,    Columna: " + (yycolumn+1));
                                    listaErrores.add(e);*/
          }
        case 59: break;
        case 49: 
          { System.out.println(yytext()); return new Symbol(SimbolosCPP.SCANF, yycolumn, yyline, yytext());
          }
        case 60: break;
        case 30: 
          { System.out.println("MAS_MAS"); return new Symbol(SimbolosCPP.MAS_MAS , yycolumn, yyline, yytext());
          }
        case 61: break;
        case 15: 
          { System.out.println("MAYOR_QUE"); return new Symbol(SimbolosCPP.MAYOR_QUE , yycolumn, yyline, yytext());
          }
        case 62: break;
        case 23: 
          { System.out.println("LLAVES CIEERRE"); return new Symbol(SimbolosCPP.LLAVES_C , yycolumn, yyline, yytext());
          }
        case 63: break;
        case 45: 
          { System.out.println(yytext()); return new Symbol(SimbolosCPP.VOID, yycolumn, yyline, yytext());
          }
        case 64: break;
        case 43: 
          { System.out.println(yytext()); return new Symbol(SimbolosCPP.ELSE , yycolumn, yyline, yytext());
          }
        case 65: break;
        case 31: 
          { System.out.println("MENOS_MENOS"); return new Symbol(SimbolosCPP.MENOS_MENOS , yycolumn, yyline, yytext());
          }
        case 66: break;
        case 42: 
          { System.out.println(yytext()); return new Symbol(SimbolosCPP.CHAR , yycolumn, yyline, yytext());
          }
        case 67: break;
        case 9: 
          { System.out.println(yytext()); return new Symbol(SimbolosCPP.NOT , yycolumn, yyline, yytext());
          }
        case 68: break;
        case 25: 
          { System.out.println(yytext()); return new Symbol(SimbolosCPP.IF , yycolumn, yyline, yytext());
          }
        case 69: break;
        case 8: 
          { System.out.println(yytext()); return new Symbol(SimbolosCPP.ANDPERSAND , yycolumn, yyline, yytext());
          }
        case 70: break;
        case 44: 
          { System.out.println("Comentario: "+yytext()); return new Symbol(SimbolosCPP.COMENTARIO_VARIOS , yycolumn, yyline, yytext());
          }
        case 71: break;
        case 24: 
          { System.out.println("COMA"); return new Symbol(SimbolosCPP.COMA , yycolumn, yyline, yytext());
          }
        case 72: break;
        case 12: 
          { System.out.println("ASTERISCO"); return new Symbol(SimbolosCPP.POR , yycolumn, yyline, yytext());
          }
        case 73: break;
        case 38: 
          { System.out.println(yytext()); return new Symbol(SimbolosCPP.INT , yycolumn, yyline, yytext());
          }
        case 74: break;
        case 13: 
          { System.out.println("DIV"); return new Symbol(SimbolosCPP.DIV , yycolumn, yyline, yytext());
          }
        case 75: break;
        case 46: 
          { System.out.println(yytext()); return new Symbol(SimbolosCPP.CONSTANTE , yycolumn, yyline, yytext());
          }
        case 76: break;
        case 41: 
          { System.out.println(yytext()); return new Symbol(SimbolosCPP.CASE , yycolumn, yyline, yytext());
          }
        case 77: break;
        case 40: 
          { System.out.println("Comentario: "+yytext()); return new Symbol(SimbolosCPP.COMENTARIO_SIMPLE , yycolumn, yyline, yytext());
          }
        case 78: break;
        case 21: 
          { System.out.println("CORCHE CIERRE"); return new Symbol(SimbolosCPP.CORCHETE_C , yycolumn, yyline, yytext());
          }
        case 79: break;
        case 26: 
          { System.out.println("do"); return new Symbol(SimbolosCPP.DO , yycolumn, yyline, yytext());
          }
        case 80: break;
        case 55: 
          { System.out.println(yytext()); return new Symbol(SimbolosCPP.INCLUDE , yycolumn, yyline, yytext());
          }
        case 81: break;
        case 52: 
          { System.out.println(yytext()); return new Symbol(SimbolosCPP.BREAK , yycolumn, yyline, yytext());
          }
        case 82: break;
        case 34: 
          { System.out.println("IGUAL_IGUAL"); return new Symbol(SimbolosCPP.IGUAL_IGUAL , yycolumn, yyline, yytext());
          }
        case 83: break;
        case 33: 
          { System.out.println("MAYOR_IGUAL"); return new Symbol(SimbolosCPP.MAYOR_IGUAL , yycolumn, yyline, yytext());
          }
        case 84: break;
        case 35: 
          { System.out.println(yytext()); return new Symbol(SimbolosCPP.VALOR , yycolumn, yyline, yytext());
          }
        case 85: break;
        case 29: 
          { System.out.println("DIFERENTE"); return new Symbol(SimbolosCPP.DIFERENTE , yycolumn, yyline, yytext());
          }
        case 86: break;
        case 58: 
          { System.out.println(yytext()); return new Symbol(SimbolosCPP.SEPARADOR_PROGRAMA , yycolumn, yyline, yytext());
          }
        case 87: break;
        case 6: 
          { System.out.println("PARENTESIS_A"); return new Symbol(SimbolosCPP.PARENTESIS_A , yycolumn, yyline, yytext());
          }
        case 88: break;
        case 16: 
          { System.out.println("IGUAL"); return new Symbol(SimbolosCPP.IGUAL , yycolumn, yyline, yytext());
          }
        case 89: break;
        case 11: 
          { System.out.println("MENOS"); return new Symbol(SimbolosCPP.MENOS , yycolumn, yyline, yytext());
          }
        case 90: break;
        case 50: 
          { System.out.println(yytext()); return new Symbol(SimbolosCPP.SWITCH , yycolumn, yyline, yytext());
          }
        case 91: break;
        case 14: 
          { System.out.println("MENOR_QUE"); return new Symbol(SimbolosCPP.MENOR_QUE , yycolumn, yyline, yytext());
          }
        case 92: break;
        case 22: 
          { System.out.println("LLAVES ABRE"); return new Symbol(SimbolosCPP.LLAVES_A , yycolumn, yyline, yytext());
          }
        case 93: break;
        case 47: 
          { System.out.println(yytext()); return new Symbol(SimbolosCPP.FLOAT , yycolumn, yyline, yytext());
          }
        case 94: break;
        case 53: 
          { System.out.println(yytext()); return new Symbol(SimbolosCPP.GETCH, yycolumn, yyline, yytext());
          }
        case 95: break;
        case 37: 
          { System.out.println("DECIMAL: "+yytext()); return new Symbol(SimbolosCPP.DECIMAL , yycolumn, yyline, yytext());
          }
        case 96: break;
        case 48: 
          { System.out.println("while"); return new Symbol(SimbolosCPP.WHILE , yycolumn, yyline, yytext());
          }
        case 97: break;
        case 19: 
          { System.out.println("punto"); return new Symbol(SimbolosCPP.PUNTO , yycolumn, yyline, yytext());
          }
        case 98: break;
        case 5: 
          { System.out.println("Modulo"); return new Symbol(SimbolosCPP.MODULO , yycolumn, yyline, yytext());
          }
        case 99: break;
        case 56: 
          { System.out.println(yytext()); return new Symbol(SimbolosCPP.CLEARS, yycolumn, yyline, yytext());
          }
        case 100: break;
        case 28: 
          { System.out.println(yytext()); return new Symbol(SimbolosCPP.OR , yycolumn, yyline, yytext());
          }
        case 101: break;
        case 7: 
          { System.out.println("PARENTESIS_C"); return new Symbol(SimbolosCPP.PARENTESIS_C , yycolumn, yyline, yytext());
          }
        case 102: break;
        case 2: 
          { System.out.println("id: "+yytext()); return new Symbol(SimbolosCPP.IDENTIFICADOR , yycolumn, yyline, yytext());
          }
        case 103: break;
        case 39: 
          { System.out.println("for"); return new Symbol(SimbolosCPP.FOR , yycolumn, yyline, yytext());
          }
        case 104: break;
        case 27: 
          { System.out.println(yytext()); return new Symbol(SimbolosCPP.AND , yycolumn, yyline, yytext());
          }
        case 105: break;
        case 51: 
          { System.out.println(yytext()); return new Symbol(SimbolosCPP.RETURN , yycolumn, yyline, yytext());
          }
        case 106: break;
        case 32: 
          { System.out.println("MENOR_IGUAL"); return new Symbol(SimbolosCPP.MENOR_IGUAL , yycolumn, yyline, yytext());
          }
        case 107: break;
        case 4: 
          { /*Ignore*/
          }
        case 108: break;
        case 10: 
          { System.out.println("MAS"); return new Symbol(SimbolosCPP.MAS , yycolumn, yyline, yytext());
          }
        case 109: break;
        case 36: 
          { System.out.println(yytext()); return new Symbol(SimbolosCPP.TEXTO , yycolumn, yyline, yytext());
          }
        case 110: break;
        case 18: 
          { System.out.println("dos puntos"); return new Symbol(SimbolosCPP.DOS_PUNTOS , yycolumn, yyline, yytext());
          }
        case 111: break;
        case 20: 
          { System.out.println("CHORCHETE ABRE"); return new Symbol(SimbolosCPP.CORCHETE_A , yycolumn, yyline, yytext());
          }
        case 112: break;
        case 3: 
          { System.out.println("NUMERO: "+yytext()); return new Symbol(SimbolosCPP.NUMERO , yycolumn, yyline, yytext());
          }
        case 113: break;
        case 57: 
          { System.out.println(yytext()); return new Symbol(SimbolosCPP.DEFAULT , yycolumn, yyline, yytext());
          }
        case 114: break;
        case 17: 
          { System.out.println("PUNTO_COMA"); return new Symbol(SimbolosCPP.PUNTO_COMA , yycolumn, yyline, yytext());
          }
        case 115: break;
        case 54: 
          { System.out.println("Mensaje: "+yytext()); return new Symbol(SimbolosCPP.PRINTF , yycolumn, yyline, yytext());
          }
        case 116: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(SimbolosCPP.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
