
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 15 06:50:41 CST 2020
//----------------------------------------------------

package analisis.cpp;

/** CUP generated class containing symbol constants. */
public class SimbolosCPP {
  /* terminals */
  public static final int MAS_MAS = 12;
  public static final int NUMERO = 43;
  public static final int SCANF = 5;
  public static final int POR = 17;
  public static final int CHAR = 27;
  public static final int LLAVES_C = 52;
  public static final int LLAVES_A = 51;
  public static final int COMENTARIO_VARIOS = 29;
  public static final int CASE = 37;
  public static final int DIFERENTE = 24;
  public static final int MENOS_MENOS = 14;
  public static final int DOS_PUNTOS = 48;
  public static final int VB_ALL = 64;
  public static final int CORCHETE_C = 50;
  public static final int INT = 25;
  public static final int CORCHETE_A = 49;
  public static final int VB = 58;
  public static final int FOR = 31;
  public static final int CONSTANTE = 4;
  public static final int IDENTIFICADOR = 42;
  public static final int NOT = 11;
  public static final int AND = 9;
  public static final int IGUAL = 47;
  public static final int JV_ONE = 61;
  public static final int OR = 10;
  public static final int DIV = 18;
  public static final int IF = 34;
  public static final int PUNTO_COMA = 53;
  public static final int IGUAL_IGUAL = 23;
  public static final int DECIMAL = 44;
  public static final int EOF = 0;
  public static final int RETURN = 41;
  public static final int SEPARADOR_PROGRAMA = 2;
  public static final int JV_ALL = 60;
  public static final int error = 1;
  public static final int COMA = 54;
  public static final int GETCH = 7;
  public static final int INCLUDE = 3;
  public static final int MODULO = 16;
  public static final int MENOS = 15;
  public static final int MAYOR_QUE = 20;
  public static final int PY_ONE = 63;
  public static final int BREAK = 38;
  public static final int PRINTF = 30;
  public static final int SWITCH = 36;
  public static final int COMENTARIO_SIMPLE = 28;
  public static final int VALOR = 45;
  public static final int ELSE = 35;
  public static final int MAIN_INT = 66;
  public static final int PUNTO = 57;
  public static final int PARENTESIS_C = 56;
  public static final int WHILE = 32;
  public static final int PARENTESIS_A = 55;
  public static final int DEFAULT = 39;
  public static final int MAYOR_IGUAL = 22;
  public static final int ANDPERSAND = 8;
  public static final int FLOAT = 26;
  public static final int PY_ALL = 65;
  public static final int MENOR_QUE = 19;
  public static final int TEXTO = 46;
  public static final int MENOR_IGUAL = 21;
  public static final int CLEARS = 6;
  public static final int JV = 67;
  public static final int PY = 59;
  public static final int MAIN_VOID = 40;
  public static final int DO = 33;
  public static final int VB_ONE = 62;
  public static final int MAS = 13;
}

